backend:
  name: github
  repo: suzette-sousa/suzette-sousa.github.io
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: test
    label: Test
    folder: "content/test"
    create: true
    slug: "{{name}}"
    identifier_field: name
    fields:
      - {name: name, label: name, widget: string}
      - name: categorie
        widget: list
        field: {
          label: "categorie",
          name: "categorie",
          widget: "relation",
          collection: "categories",
          search_fields: ["name"],
          value_field: "name",
          display_fields: ["name"]
        }
  - name: categories
    label: Categories
    folder: "content/categories"
    create: true
    slug: "{{name}}"
    identifier_field: name
    fields: 
      - {name: name, label: Name}

  - name: "pages"
    label: "Pages"
    files:
    - label: "Portfolio"
      name: "portfolio"
      file: "content/portfolio.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: "Projets"
          name: "projets"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text", required: false}
            - { label: "Image", name: "thumbnail", alt: "alt", widget: "image"}
            - { label: "Link", name: "link", url: "/", widget: "string"}
            - { label: "Date", name: "date", widget: "datetime", default: "01/01/2013", date_format: "DD/MM/YYYY", time_format: false, format: "DD/MM/YYYY" }
            - name: categories
              widget: list
              field: {
                label: "category",
                name: "category",
                widget: "relation",
                collection: "categories",
                search_fields: ["name"],
                value_field: "name",
                display_fields: ["name"]
              }
    - label: "Skills"
      name: "skills"
      file: "content/skills.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Certifications'
          name: "certifs"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
            - { label: "Date obtention", name: "date", widget: "datetime" }
            - { label: "Image", name: "thumbnail", alt: "alt", widget: "image"}
            - { label: "Link", name: "link", url: "/", widget: "string"}