backend:
  name: github
  repo: suzette-sousa/suzette-sousa.github.io
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Projets'
          name: "projets"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
            - { label: "Image", name: "thumbnail", alt: "alt", widget: "image"}
            - { label: "Link", name: "link", url: "/", widget: "string"}